title: Kwan Yu Kim from KOR
description: Personal homepage for Kwanyu Kim, from South Korea.

# Theme settings
remote_theme: sighingnow/jekyll-gitbook

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# Sidebar order
ordered_collections:
  - pages

# Plugins
plugins:
  - jekyll-remote-theme
